pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=build (3.11)
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
      - label=ready-to-merge
    actions:
      merge:
        method: squash
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: automatic merge for pyUp pull requests
    conditions:
      - author=pyup-bot
      - status-success=build (3.11)
      - label=dependencies
    actions:
      merge:
        method: squash
  - name: automatic merge for dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=build (3.11)
      - label=dependencies
    actions:
      merge:
        method: squash
  - name: Automatically approve Dependabot PRs
    conditions:
      - author = dependabot[bot]
    actions:
      review:
        type: APPROVE
