language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - TEST=-v
  matrix:
    - DOCUTILS=0.14

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: pypy

install:
  - pip install -U pip
  - pip install docutils==$DOCUTILS
  - pip install -r requirements.txt

script:
  - make html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build/html/
  keep-history: true
  on:
    branch: master
    python: 3.6
